version: '3.8'

services:
  mysql_dev:
    build: mysql
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
      MYSQL_DATABASE: "shoppcrypto_dev"
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - mysql-compose-network

  adminer:
    image: adminer
    ports:
      - 8080:8080
    networks:
      - mysql-compose-network

  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: "root"
      MONGO_INITDB_ROOT_PASSWORD: "123456"
    volumes:
      - mongodb-data:/data/db
    networks:
      - mongodb-network
    ports:
      - "27017:27017"


  mongo-express:
    image: mongo-express
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: 123465
      ME_CONFIG_MONGODB_URL: mongodb://root:123456@mongo:27017/

    depends_on:
      - mongo
    networks:
      - mongodb-network
    ports:
      - "8081:8081"


networks: 
  mysql-compose-network:
    driver: bridge
  mongodb-network:
    driver: bridge

volumes:
  mysql-data: {}
  mongodb-data: {}
