version: '3.8'

services:
  mysql_dev:
    build: mysql
    env_file:
      - .env
    ports:
      - ${MYSQL_PORT}:${MYSQL_PORT}
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - mysql-compose-network

  adminer:
    image: adminer
    env_file:
      - .env
    ports:
      - ${ADMINER_PORT}:${ADMINER_PORT}
    networks:
      - mysql-compose-network

  mongo:
    image: mongo
    env_file:
      - .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
    volumes:
      - mongodb-data:/data/db
    networks:
      - mongodb-network
    ports:
      - ${MONGO_PORT}:${MONGO_PORT}


  mongo-express:
    image: mongo-express
    env_file:
      - .env
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: 123465
      ME_CONFIG_MONGODB_URL: mongodb://${MONGO_ROOT_USERNAME}:${MONGO_ROOT_PASSWORD}@mongo:${MONGO_PORT}/

    depends_on:
      - mongo
    networks:
      - mongodb-network
    ports:
      - ${MONGO_EXPRESS_PORT}:${MONGO_EXPRESS_PORT}


networks: 
  mysql-compose-network:
    driver: bridge
  mongodb-network:
    driver: bridge

volumes:
  mysql-data: {}
  mongodb-data: {}
